create table NOTE_CATEGORY (ID,DESCRIPTION);

CREATE TABLE NOTE_CATEGORY (
	ID NUMBER(10), 
	DESCRIPTION VARCHAR2(150)
);
CREATE UNIQUE INDEX ix_NOTE_CATEGORY_ID_PK ON NOTE_CATEGORY (ID);

ALTER TABLE NOTE_CATEGORY ADD (
  CONSTRAINT ix_NOTE_CATEGORY_ID_PK  PRIMARY KEY  (ID)
  );
