CREATE TABLE RelGroupArea (
    geoAreaId INTEGER,
    groupId   INTEGER
);

CREATE UNIQUE INDEX GROUPIDGEOAREAID_PK ON RELGROUPAREA
(GEOAREAID, GROUPID);

ALTER TABLE RELGROUPAREA ADD (
  CONSTRAINT GROUPIDGEOAREAID_PK  PRIMARY KEY  (GEOAREAID, GROUPID)
  );

ALTER TABLE RELGROUPAREA ADD (
  CONSTRAINT GEOAREAID_RELGROUPAREA_FK 
  FOREIGN KEY (GEOAREAID) REFERENCES GEOAREA (ID),
  CONSTRAINT GROUPID_RELGROUPAREA_FK 
  FOREIGN KEY (GROUPID) REFERENCES GROUPS (ID)
  );

