CREATE TABLE RelUserGroups (
    userId INTEGER,
    groupId   INTEGER
);

CREATE UNIQUE INDEX userIdGROUPID_PK ON RelUserGroups
(userId, GROUPID);

ALTER TABLE RelUserGroups ADD (
  CONSTRAINT userIdGROUPID_PK  PRIMARY KEY  (userId, GROUPID)
  );

ALTER TABLE RelUserGroups ADD (
  CONSTRAINT userId_RelUserGroups_FK 
  FOREIGN KEY (userId) REFERENCES USERS (ID),
  CONSTRAINT GROUPID_RelUserGroups_FK 
  FOREIGN KEY (GROUPID) REFERENCES GROUPS (ID)
  );