create table USERS (
id INTEGER, 
name VARCHAR(50), 
password VARCHAR(30), 
fullname VARCHAR(50),
ISADMIN NUMBER(1,0) DEFAULT 0
);

CREATE UNIQUE INDEX ix_Users_PK on USERS (name);

ALTER TABLE USERS ADD (
  CONSTRAINT USERID_PK PRIMARY KEY(ID)
);