CREATE TABLE ALLATTR
(
  ID          NUMBER,
  ATTRTYPEID  NUMBER,
  IDX         NUMBER,
  VAL         VARCHAR2(100 BYTE)
);

CREATE UNIQUE INDEX IX_ALLATTR_PK ON ALLATTR
(ID, ATTRTYPEID, IDX);


ALTER TABLE ALLATTR ADD (
  CONSTRAINT IX_ALLATTR_PK
  UNIQUE (ID, ATTRTYPEID, IDX)
  USING INDEX IX_ALLATTR_PK
  ENABLE VALIDATE);
