CREATE TABLE CfgAreaType
(
  ID          NUMBER,
  DSC  	      VARCHAR2(100 BYTE),
  CODE        VARCHAR2(100 BYTE),
  PARENT      NUMBER
);

CREATE UNIQUE INDEX IX_CFGAREATYPE_PK ON CFGAREATYPE
(ID);

ALTER TABLE CFGAREATYPE ADD (
  CONSTRAINT IX_CFGAREATYPE_PK
  PRIMARY KEY
  (ID)
  USING INDEX IX_CFGAREATYPE_PK);
