CREATE TABLE USERPOINTS1(
id INTEGER,
x INTEGER,
y INTEGER,
description VARCHAR (100),
icon_id INTEGER,
angle FLOAT,
scale FLOAT,
color FLOAT
);

CREATE UNIQUE INDEX IDUSERPOINT_PK ON USERPOINTS1(ID);

ALTER TABLE USERPOINTS1 ADD (
  CONSTRAINT IDUSERPOINT_PK PRIMARY KEY(ID)
);