create table USERS (
id INTEGER, 
name VARCHAR(50), 
password VARCHAR(30), 
fullname VARCHAR(50),
ISADMIN NUMBER(1,0) DEFAULT 0
);

CREATE UNIQUE INDEX ix_Users_DSC on USERS (name);
CREATE UNIQUE INDEX ix_Users_PK on USERS (ID);
