SELECT *
FROM(
            SELECT HUB,SUBREGION,REGION,UDN,COEF,SITIO,ATENCION,BASE,BBI_ESTADOS,BBI_FHAB,COOPERATIVAS,OM,MODULADOR,CONTROLADORA,
            PROVISIONING,TOPOLOGIA,INFLUENCIA,ANTENA_WIMAX,INFLUENCIA_WIMAX,EMPRESA,MAX_VEL_ACC,FECHA_CAMBIO_VEL,MAX_VEL_ACC_OLD,
            ID_BASE_OPEN,LOGIDFROM, to_char(DATEFROM,'YYYY-MM-DD HH24:MI:SS')  DATEFROM,LOGIDTO,to_char(DATETO,'YYYY-MM-DD HH24:MI:SS' ) DATETO,row_number() over (order by logIdFrom, hub)  rn
            FROM GIS_DET_HUB_H
            ) rn
WHERE rn BETWEEN $rownumMin AND $rownumMax