SELECT o.OBJECTID ObjectId, o.LinkId AttrTypeId, o.SeqOrder Idx, RTRIM(o.LINKVALUE) Val
FROM SPRLINKS o, SPRLOG lf
WHERE 
o.LOGIDTO=0 AND $logIdSyncMin < o.LOGIDFROM AND o.LOGIDFROM <= $logIdSyncMax
AND o.LOGIDFROM=lf.LOGID AND lf.EVENTSTATUS=0 
