SELECT  v.BLOCKID GeoBlockId, v.BLOCKGEOORDER Idx
, round(v.x*10,0) X, round(v.y*10,0) Y
FROM SMBLOCKGEO v, SMBLOCKS o
, SPRLOG lf
WHERE v.BLOCKID=o.BLOCKID
AND o.LOGIDTO=0 AND $logIdSyncMin < o.LOGIDFROM AND o.LOGIDFROM <= $logIdSyncMax
AND o.LOGIDFROM=lf.LOGID AND lf.EVENTSTATUS=0 
