SELECT  v.BLOCKID GeoBlockId, v.BLOCKGEOORDER Idx
FROM SMBLOCKGEO v, SMBLOCKS o
, SPRLOG lf
WHERE v.BLOCKID=o.BLOCKID
AND o.LOGIDTO!=0 AND $logIdSyncMin < o.LOGIDTO AND o.LOGIDTO <= $logIdSyncMax
AND o.LOGIDTO=lf.LOGID AND lf.EVENTSTATUS=0 