SELECT lf.LOGID,lt.LOGID, l.OBJECTID,RTRIM(l.LINKVALUE),to_char(l.DATEFROM,'YYYY-MM-DD HH24:MI:SS') DATEFROM
FROM SPRLINKS l, SPRLOG lf, SPRLOG lt
WHERE l.LOGIDFROM=lf.LOGID
AND l.LOGIDTO=lt.LOGID AND lf.EVENTSTATUS=0 AND lt.EVENTSTATUS=0 AND lt.LOGID!=0 AND lf.LOGID>$logidsync 
AND ROWNUM<10
