SELECT o.OBJECTIDFROM,o.NODEINDEXFROM,o.OBJECTIDTO,o.NODEINDEXTO
FROM SPRTOPOLOGY o
,SPRLOG lf
WHERE o.OBJECTIDFROM>o.OBJECTIDTO AND o.TOPOLOGYTYPE=0
AND o.LOGIDTO=0 AND $logIdSyncMin < o.LOGIDFROM AND o.LOGIDFROM <= $logIdSyncMax
AND o.LOGIDFROM=lf.LOGID AND lf.EVENTSTATUS=0 
