INSERT INTO XXY.XXY_MGU_OBJECTS(
	ID, 
	CATEGORY, 
	TYPE, 
	DESCRIPTION, 
	DATE_FROM, 
	USER_ID,
	IS_OWNER, 
	MAP_ID, 
	GEOMETRY_TYPE, 
	GEOMETRY,
	X, 
	Y)
VALUES ((select max(id) + 1 from XXY.XXY_MGU_OBJECTS), 
	$category_id , 
	$category_type_id, 
	$descripcion, 
	TO_DATE($fecha_creacion, 'YYYY-MM-DD HH24:MI:SS'), 
	$userId, 
	1, 
	10, 
	'point', 
	SDO_GEOMETRY(2001, NULL, SDO_POINT_TYPE( $x, $y,NULL), NULL, NULL), 
	$x, 
	$y)